### PR TITLE
SRE-247 Add CWEE support

### PR DESCRIPTION
**Pull request by dimoschi**
## Types of changes

What types of changes does your code introduce?
*Put an `x` in the boxes that apply.*

- [ ] Bugfix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).
- [ ] Documentation Update (if none of the other choices applies).

## Proposed changes

Add support for CWEE

## Checklist

*Put an `x` in the boxes that apply.*

- [x] I have read and followed the [CONTRIBUTING.md](https://github.com/hackthebox/Hackster/blob/main/CONTRIBUTING.md)
  doc.
- [x] Lint and unit tests pass locally with my changes.
- [ ] I have added the necessary documentation (if appropriate).

## Additional context

No additional context

### CODE REVIEW

**Review by makelarisjr — APPROVED** [review]
LGTM!

**Review by 0xEmma — APPROVED** [review]

**Comment by 0xEmma** [comment]
LGTM

**Comment by makelarisjr** [comment]
@0xEmma Can you provide the ids for the CDSA and CWEE roles?

**Comment by dimoschi** [comment]
Merged, but let's wait to deploy on Tuesday, since we have a long weekend ahead.

**Comment by 0xEmma** [comment]
CDSA = 1157697238949167235
CWEE = 1210237317118427156 
@makelarisjr

**Pull request merged**
