### PR TITLE
[FEATURE] - Add option to `/support` for sending Academy support link

### PR DESCRIPTION
**Pull request by janssensjelle**
## Types of changes

What types of changes does your code introduce?
*Put an `x` in the boxes that apply.*

- [ ] Bugfix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).
- [ ] Documentation Update (if none of the other choices applies).

## Proposed changes

Adds the option to provide a link to Academy support via `/support` . This will allow the person who runs the command to choose between "labs" and "academy". Labs is default. Screenshots in comment below.

## Checklist

*Put an `x` in the boxes that apply.*

- [X] I have read and followed the [CONTRIBUTING.md](https://github.com/hackthebox/Hackster/blob/main/CONTRIBUTING.md)
  doc.
- [X] Lint and unit tests pass locally with my changes.
- [X] I have added the necessary documentation (if appropriate).

### CODE REVIEW

**Review by dimoschi — COMMENTED** [review]
Would it make sense to combine the commands `support` and `academysupport` and use a parameter to make the distinction? Whatever you feel like.

**Comment by janssensjelle** [comment]
Combined this with `/support`. Made it an option list with default "labs"

Received false positive lint error
```
src/cmds/core/other.py:78:67: F821 undefined name 'labs'
src/cmds/core/other.py:78:75: F821 undefined name 'academy'
src/cmds/core/other.py:78:95: F821 undefined name 'labs'
```

Screenshot 2024-11-22 at 10 51 00
Screenshot 2024-11-22 at 10 51 15

**Review by dimoschi — CHANGES_REQUESTED** [review]
It would make sense in tests to check that the URL is different for each call. I understand that this is minor, but it would much better.

**Comment by janssensjelle** [comment]
@dimoschi I've added the requested test.

There's three tests for this now:

1. Labs must be URL x
2. Academy must by URL y
3. Academy must be different from Labs

**Review by janssensjelle — COMMENTED** [review]
I've added additional tests

**Pull request merged**
