### PR TITLE
kindly doing the needful

### PR DESCRIPTION
**Pull request by cre4k**
## Types of changes

What types of changes does your code introduce?
*Put an `x` in the boxes that apply.*

- [ ] Bugfix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).
- [ ] Documentation Update (if none of the other choices applies).

## Proposed changes

cre4k

## Checklist

*Put an `x` in the boxes that apply.*

- [x] I have read and followed the [CONTRIBUTING.md](https://github.com/hackthebox/Hackster/blob/main/CONTRIBUTING.md)
  doc.
- [x] Lint and unit tests pass locally with my changes.
- [x] I have added the necessary documentation (if appropriate).

## Additional context

cre4k

### CODE REVIEW

**Comment by daanbreur** [comment]
Amazing Quality PR! 👏 👏 👏 
Merge this right away!

**Comment by cre4k** [comment]
> shouldn't the function be named cre4k instead of start_here

we don't need that function anymore, this one is better

**Comment by cre4k** [comment]
I suppose you could change it if you want

**Comment by daanbreur** [comment]
Amazing pr this has to be merged

**Review by daanbreur — COMMENTED** [review]
+1

**Comment by 0xEmma** [comment]
I will kindly do the needful, and close this as this is not needed.

**Comment by cre4k** [comment]
> I will kindly do the needful, and close this as this is not needed.

I'd argue on the contrary
Give the people what they want!!!

**Pull request closed without merging**
